/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiConversationsRouteImport } from './routes/ai-conversations'
import { Route as AnnotationsRouteImport } from './routes/annotations'
import { Route as DigestsRouteImport } from './routes/digests'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LaterRouteImport } from './routes/later'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as StarredRouteImport } from './routes/starred'
import { Route as SourcesIndexRouteImport } from './routes/sources.index'
import { Route as SourcesSourceIDRouteImport } from './routes/sources.$sourceID'
import { Route as StoriesStoryIDRouteImport } from './routes/stories.$storyID'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiConversationsRoute = AiConversationsRouteImport.update({
  id: '/ai-conversations',
  path: '/ai-conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnotationsRoute = AnnotationsRouteImport.update({
  id: '/annotations',
  path: '/annotations',
  getParentRoute: () => rootRouteImport,
} as any)
const DigestsRoute = DigestsRouteImport.update({
  id: '/digests',
  path: '/digests',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LaterRoute = LaterRouteImport.update({
  id: '/later',
  path: '/later',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const StarredRoute = StarredRouteImport.update({
  id: '/starred',
  path: '/starred',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesIndexRoute = SourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SourcesRoute,
} as any)
const SourcesSourceIDRoute = SourcesSourceIDRouteImport.update({
  id: '/$sourceID',
  path: '/$sourceID',
  getParentRoute: () => SourcesRoute,
} as any)
const StoriesStoryIDRoute = StoriesStoryIDRouteImport.update({
  id: '/stories/$storyID',
  path: '/stories/$storyID',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-conversations': typeof AiConversationsRoute
  '/annotations': typeof AnnotationsRoute
  '/digests': typeof DigestsRoute
  '/inbox': typeof InboxRoute
  '/later': typeof LaterRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRouteWithChildren
  '/starred': typeof StarredRoute
  '/sources/$sourceID': typeof SourcesSourceIDRoute
  '/stories/$storyID': typeof StoriesStoryIDRoute
  '/sources/': typeof SourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-conversations': typeof AiConversationsRoute
  '/annotations': typeof AnnotationsRoute
  '/digests': typeof DigestsRoute
  '/inbox': typeof InboxRoute
  '/later': typeof LaterRoute
  '/settings': typeof SettingsRoute
  '/starred': typeof StarredRoute
  '/sources/$sourceID': typeof SourcesSourceIDRoute
  '/stories/$storyID': typeof StoriesStoryIDRoute
  '/sources': typeof SourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-conversations': typeof AiConversationsRoute
  '/annotations': typeof AnnotationsRoute
  '/digests': typeof DigestsRoute
  '/inbox': typeof InboxRoute
  '/later': typeof LaterRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRouteWithChildren
  '/starred': typeof StarredRoute
  '/sources/$sourceID': typeof SourcesSourceIDRoute
  '/stories/$storyID': typeof StoriesStoryIDRoute
  '/sources/': typeof SourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-conversations'
    | '/annotations'
    | '/digests'
    | '/inbox'
    | '/later'
    | '/settings'
    | '/sources'
    | '/starred'
    | '/sources/$sourceID'
    | '/stories/$storyID'
    | '/sources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-conversations'
    | '/annotations'
    | '/digests'
    | '/inbox'
    | '/later'
    | '/settings'
    | '/starred'
    | '/sources/$sourceID'
    | '/stories/$storyID'
    | '/sources'
  id:
    | '__root__'
    | '/'
    | '/ai-conversations'
    | '/annotations'
    | '/digests'
    | '/inbox'
    | '/later'
    | '/settings'
    | '/sources'
    | '/starred'
    | '/sources/$sourceID'
    | '/stories/$storyID'
    | '/sources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiConversationsRoute: typeof AiConversationsRoute
  AnnotationsRoute: typeof AnnotationsRoute
  DigestsRoute: typeof DigestsRoute
  InboxRoute: typeof InboxRoute
  LaterRoute: typeof LaterRoute
  SettingsRoute: typeof SettingsRoute
  SourcesRoute: typeof SourcesRouteWithChildren
  StarredRoute: typeof StarredRoute
  StoriesStoryIDRoute: typeof StoriesStoryIDRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-conversations': {
      id: '/ai-conversations'
      path: '/ai-conversations'
      fullPath: '/ai-conversations'
      preLoaderRoute: typeof AiConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annotations': {
      id: '/annotations'
      path: '/annotations'
      fullPath: '/annotations'
      preLoaderRoute: typeof AnnotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digests': {
      id: '/digests'
      path: '/digests'
      fullPath: '/digests'
      preLoaderRoute: typeof DigestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/later': {
      id: '/later'
      path: '/later'
      fullPath: '/later'
      preLoaderRoute: typeof LaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/starred': {
      id: '/starred'
      path: '/starred'
      fullPath: '/starred'
      preLoaderRoute: typeof StarredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/': {
      id: '/sources/'
      path: '/'
      fullPath: '/sources/'
      preLoaderRoute: typeof SourcesIndexRouteImport
      parentRoute: typeof SourcesRoute
    }
    '/sources/$sourceID': {
      id: '/sources/$sourceID'
      path: '/$sourceID'
      fullPath: '/sources/$sourceID'
      preLoaderRoute: typeof SourcesSourceIDRouteImport
      parentRoute: typeof SourcesRoute
    }
    '/stories/$storyID': {
      id: '/stories/$storyID'
      path: '/stories/$storyID'
      fullPath: '/stories/$storyID'
      preLoaderRoute: typeof StoriesStoryIDRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SourcesRouteChildren {
  SourcesSourceIDRoute: typeof SourcesSourceIDRoute
  SourcesIndexRoute: typeof SourcesIndexRoute
}

const SourcesRouteChildren: SourcesRouteChildren = {
  SourcesSourceIDRoute: SourcesSourceIDRoute,
  SourcesIndexRoute: SourcesIndexRoute,
}

const SourcesRouteWithChildren =
  SourcesRoute._addFileChildren(SourcesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiConversationsRoute: AiConversationsRoute,
  AnnotationsRoute: AnnotationsRoute,
  DigestsRoute: DigestsRoute,
  InboxRoute: InboxRoute,
  LaterRoute: LaterRoute,
  SettingsRoute: SettingsRoute,
  SourcesRoute: SourcesRouteWithChildren,
  StarredRoute: StarredRoute,
  StoriesStoryIDRoute: StoriesStoryIDRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
